name: Build Android APK (Debug)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # PERBAIKAN: Menambahkan langkah untuk menginstal Android Command Line Tools
      # yang diperlukan oleh make.sh dan Gradle
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: '34' # Sesuaikan dengan target API level proyek Anda
          cmdline-tools: true 

      - name: Grant execute permission for gradlew and make.sh
        run: |
          chmod +x gradlew
          chmod +x make.sh

      - name: Build Debug APK via make.sh
        # Menggunakan "debug" adalah panggilan yang paling mendekati "build"
        run: ./make.sh debug 

      # PERBAIKAN: Indentasi yang benar untuk upload-artifact
      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Complete job
        run: echo "Build successful and artifact uploaded!"
