name: Build Android APK (Debug)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout Code

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    # LANGKAH BARU UNTUK KONFIGURASI ANDROID SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      # Parameter versi SDK bisa disesuaikan, tapi 34 adalah yang terbaru
      with:
        api-level: 34
        build-tools: 34.0.0

    - name: Grant execute permission for gradlew and make.sh
      run: |
        chmod +x gradlew
        chmod +x make.sh

    - name: Build Debug APK via make.sh
      # Perintah ini akan menggunakan make.sh yang membaca webapk.conf
      run: ./make.sh debug

    - name: Upload Debug APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
