name: Build Android APK (Debug)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout Code

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew and make.sh
      run: |
        chmod +x gradlew
        chmod +x make.sh

    - name: Build Debug APK via make.sh
      # Perintah ini akan menggunakan make.sh yang membaca webapk.conf
      run: ./make.sh debug

    - name: Upload Debug APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        # Path output standar setelah menjalankan make.sh debug
        path: app/build/outputs/apk/debug/app-debug.apk
