# .github/workflows/android-build.yml (Hanya perbarui bagian Setup Android SDK)

# ... (bagian checkout, dll. sebelumnya)

      - name: Set up Android SDK
        # Menggunakan versi yang direkomendasikan untuk stabilitas
        uses: android-actions/setup-android@v3 
        with:
          api-level: 34 # Target SDK Android
          cmdline-tools: latest

# ... (langkah-langkah berikutnya: Grant execution, Run make.sh, Build Release APK, dll.)
